name: Docs check

on:
  push:
    paths:
    - 'include/**'
    - 'docs/**'
    - 'docs_check/**'
    - '.github/workflows/noarr_docs_check.yml'

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Install gcc
      run: sudo apt-get update && sudo apt-get install gcc-10 g++-10

    - name: Test
      run: docs_check/check
